# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98070aa2a1604b66dc46e1b2c919c4822f58b81c378b2a389e41b8e119f5510f00dd6366af12d394017436f3d517dca9dc2f841393b869630fd0fdd87bfce4bb

test:
  secret_key_base: 91ac47c4d367b051d835c108a976698865d7e1f62e40fd860570628bd98b90564b1776b2c06cc27ee725675d23ee57a1d700634f0ccf9050db5ce5af228fe725

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
